spring.application.name=ticket_webapp

spring.h2.console.enabled=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

#spring.datasource.url=jdbc:h2:mem:9475295d-e2b4-4097-8bb7-cc4b4d496e21
spring.datasource.url=jdbc:h2:file:./data/testdb;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.security.user.name=user
spring.security.user.password=user

